- index.html
- src/App.tsx
- src/img/favicon.svg
- src/pages/confirmEmailPage.tsx
- src/pages/entrance.tsx
- src/pages/main/index.tsx
- src/pages/onBoarding.tsx
- src/pages/starting.tsx
- src/redux/store.ts
- src/redux/userSlice.ts
Starting page
Entrance page
OnBoarding Page
ConfirmEmail page
+ states
> Sander pod

- src/pages/confirmEmailPage.tsx
- src/redux/userOperations.ts
- src/redux/userSlice.ts
1. Доработан запрос на подтверждение имейла, ф-ция добавлена на страницу подтверждения
2. Добавлены try-catch в запросы.
> emailVerify, try-catch

- src/App.tsx
- src/components/Header.tsx
- src/components/footer.tsx
- src/pages/addVacancy.tsx
- src/pages/calendar.tsx
- src/pages/editVacancy.tsx
- src/pages/entrance.tsx
- src/pages/main/index.tsx
- src/pages/profilePage.tsx
- src/pages/reminder.tsx
- src/pages/settingsPage.tsx
- src/pages/vacancyCard.tsx
> Sander routes

- src/components/Header.tsx
- src/components/footer.tsx
- src/components/notices/ShortNotice.tsx
- src/pages/main/index.tsx
Стили для Header + Footer, ShortNotice
> styles footer+header

- src/components/Header.tsx
- src/components/footer.tsx
- src/components/notices/ShortNotice.tsx
- src/pages/main/index.tsx
Reverts KiwiCodeSolution/VacMan#34
> Revert "styles footer+header"

- src/pages/calendar.tsx
- src/pages/entrance.tsx
- src/pages/main/index.tsx
- src/pages/profilePage.tsx
- src/pages/reminder.tsx
- src/pages/settingsPage.tsx
Стили footer'а на всех страницах
> footer at all pages

- src/components/Header.tsx
- src/components/footer.tsx
- src/components/notices/ShortNotice.tsx
Откорректированы стили. Хедер и футер закреплены.
> last styles header & footer

- src/App.tsx
- src/components/iconsComponents.tsx
- src/components/notices/FullNotice.tsx
- src/components/notices/ShortNotice.tsx
- src/components/ui/stars/index.tsx
- src/pages/Private/editVacancy.tsx
Reverts KiwiCodeSolution/VacMan#40
> Revert "Notes"

- src/components/navHeader.tsx
- src/components/notices/FullNotice.tsx
- src/components/notices/ShortNotice.tsx
- src/components/ui/loader/index.tsx
- src/redux/VacancyQueries.ts
1. Откорректированы стили лоадера: он теперь по центру
2. Дополнен NavBar: добавлена кнопка редактирования карточки, дополнены стили для корректного отображения на всех страничках
3. Исправлена полная карточка: добавлен NavBar, откорректированы поля и значения
> loader + NavBar

- src/components/notices/FullNotice.tsx
- src/components/notices/ShortNotice.tsx
1. Фон для NavHeader в полной карточке
2. Добавлено значение валюты в маленьких карточках
> currency + bg NavBar

- src/components/modals/CurrencySelectionModal.tsx
- src/components/notices/FullNotice.tsx
- src/components/notices/ShortNotice.tsx
- src/pages/Private/settingsPage.tsx
- src/redux/userSlice.ts
Создано модельное окно для выбора валюты.
На бек пока не уходит код валюты, функция отключена.
> remove comments

- src/components/notices/FullNotice.tsx
- src/components/notices/ShortNotice.tsx
- src/components/notices/actionElement.tsx
- src/components/notices/actionList.tsx
- src/components/notices/actionShortElement.tsx
Компонент для отображения временной линии в экшенах.  Пока без анимации. 
Немного исправлены стили в полной карточке.
> time-line for actions

- src/components/notices/FullNotice.tsx
- src/components/notices/ShortNotice.tsx
- src/components/notifications/index.tsx
Удален blur, информационное уведомление исчезает за 3 секунды.
В маленькой карточке удалена ссылка на названии компании.
> link shortnotice, blur+animation modal

- src/components/notices/FullNotice.tsx
- src/components/notices/ShortNotice.tsx
- src/components/notices/actionList.tsx
- src/components/reminder/ReminderItem.tsx
- src/components/ui/button/index.tsx
1. В карточках Reminder'а добавлены иконки, возможность просмотра полной карточки вакансии.
2. В полной карточке вакансии вернула кнопки "в активные" и "удалить". Они где-то потерялись до этого.
3. В компонент Button добавила свойство disabled, из-за него исправила некоторые стили на кнопке + сделала экспорт эффекта ховера и фокуса для переиспользования на других кнопках.
4. В ActionList настроила disabled кнопки добавления экшена по условию состояния последнего экшена. 
5. В ShortNote сделала экспорты эффектов для переиспользования в карточках Reminder'а.
> icons, disabled and other

- src/components/notices/FullNotice.tsx
- src/components/notices/ShortNotice.tsx
- src/components/notices/actionElement.tsx
- src/components/notices/actionList.tsx
- src/components/notices/actionShortElement.tsx
- src/components/reminder/ReminderItem.tsx
- src/components/ui/button/index.tsx
1. В полной архивной карточке поменяла местами кнопки + добавила иконки.
2. В полной карточке исправила кнопку "назад". Теперь она ведет именно назад, а не на главную.
3. В архивной карточке кнопка добавления новых экшенов неактивна всегда.
4. Исправила отображение минут в экшенах.
> fix styles

- src/components/Header.tsx
- src/components/reminder/ReminderItem.tsx
- src/pages/Private/reminder.tsx
- src/redux/userSlice.ts
- tailwind.config.cjs
1. На страничке Reminder сначала идут активные напоминания, сортированные по дате, потом выполненные (т.е. это активные вакансии, в которых последний экшен выполнен). В выполненных кнопки не активны, можно только открыть карточку вакансии на просмотр. 
2. В зависимости от близости к дедлайну колокольчик меняет цвет. Если до дедлайна больше суток - он прозрачный, если меньше суток - оранжевый, если срок прошел - то красный + анимашка.
3. В стейте юзера сделала еще одно поле reminder. Если у нас есть напоминание с просроченным дедлайном стейт меняется на true и на главной страничке становится активным колокольчик-напоминание. Не придумала еще, как его отключать :) 
4. По клику на колокольчик на главной странице можно перейти в напоминания (спорно, нужно ли?)
> fullfiled action, bell, slice

- src/components/calendar/index.tsx
- src/components/reminder/ReminderItem.tsx
- tailwind.config.cjs
1. Исправлен стиль текущей даты в календаре
2. В карточках ремаиндера зафиксирована ширина иконок (чтоб не уменьшались в случае длинного текста).
> style calendar

- src/components/calendar/index.tsx
- src/components/main.tsx
- src/pages/Private/reminder.tsx
1. На главной странице донастроила колокольчик: он становится красным и активным только в том случае, если есть задания с дедлайном меньше суток уже просроченные. Колокольчик станет неактивным если все задания выполнены или дедлайн по ним больше суток.
2. Поправила стили в календаре: текущий день отображается в прямоугольной рамке.
> color at calendar

- src/components/calendar/index.tsx
- src/components/main.tsx
- src/components/notices/FullNotice.tsx
- src/components/notices/ShortNotice.tsx
- src/components/notices/actionElement.tsx
- src/components/notices/actionList.tsx
- src/components/notices/actionShortElement.tsx
- src/components/reminder/ReminderItem.tsx
- src/components/ui/button/index.tsx
- src/pages/Private/reminder.tsx
- src/utils/stylesHelpers.tsx
- все переменные для стилей вынесла в общий файл, и, соответственно, поменяла импорты во всех файлах.
- в экшенах и в карточках ремаиндера для работы с датами использована date-fns.
- в календаре исправлены стили: все тудушки теперь помещаются на экране, не западают под панель меню.
- в полной карточке вакансии исправила ошибку, не правильно передавался пропсом background-color, исправила.
> styles, format date, styles in the calendar

- src/components/notices/actionElement.tsx
- src/components/notices/actionShortElement.tsx
- src/components/reminder/ReminderItem.tsx
1. Исправлена семантическая ошибка вложенности тегов.
2. В форматировании даты исправлен формат времени с 12часого на 24 часа
> semantic error + format date (HH)
